### ISSUE TITLE
COG block size on the webmap

### ISSUE THREAD

**Issue by drnextgis** [developmentseed/tilebench#13]
I'm visualizing COG with blocksize 256:
```
$ http "http://127.0.0.1:8081/info.geojson?ovr_level=4" | jq '.properties.ifd[4].Blocksize'
[
  256,
  256
]
```

But the web map clearly shows that tile size and block size differres:
![image](https://user-images.githubusercontent.com/866124/142722896-f745668f-ed48-4f0c-b3dd-e7761e1d0653.png)

According to the [code](https://github.com/developmentseed/tilebench/blob/master/tilebench/templates/index.html#L98) mercator tile size has the same `256px` value so I expected them to be visually identical. Am I missing something?

**Comment by vincentsarago** [comment]
it just means that your overviews are not aligned with the Mercator grid

**Comment by drnextgis** [comment]
The question was not about tiles alignment but about their dimensions. You can see that mercator grid tile bigger than COG blocks. That wasn't clear why. @vincentsarago could you please explain it?

**Comment by vincentsarago** [comment]
is the COG aligned with the mercator TMS? is the COG resolution equal to a TMS zoom level resolution?

**Comment by vincentsarago** [comment]
@drnextgis I'd love to help but please provide file so I can reproduce locally!

**Comment by drnextgis** [comment]
Ahh I see! I took a wrong assumption that their resolutions are identical bit this is not the case. Thanks!

**Comment by drnextgis** [comment]
Do you think it worth to add information about webmercator / raster resolution at selected zoom level on the webmap?

**Comment by vincentsarago** [comment]
@drnextgis feel free to start a PR with any information you think will help users 🙏
