### ISSUE TITLE
Include decorator results in response

### ISSUE THREAD

**Issue by geospatial-jeff** [developmentseed/tilebench#2]
For my use case, I have a FastAPI app and I would like to include the statistics calculated by the `profile` decorator as a response header so the caller can aggregate number of get requests and number of bytes transferred across many requests to the app.

The solution I have taken in my code is to update the function signature to be:
```python
def profile(kernels: bool = False, stderr: bool = False, add_to_return: bool = False, quiet: bool = False):
```
Where `add_to_return` optionally appends the decorator results to the response (so the response is a tuple) and `quiet` disables logging out the results via `click.echo`.

```python
from tilebench import profile

@profile(add_to_return=True, quiet=True)
def _read_tile(src_path: str, x: int, y: int, z: int, tilesize: int = 256):
    COGReader.tile(src_path, x, y, z, tilesize=tilesize)

func_resp, stats = _read_tile(
    "https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/2020/S2A_34SGA_20200318_0_L2A/B05.tif",
    2314,
    1667,
    12,
)

print(stats)

> {
  "GET_numbers": 3,
  "GET_ranges": [
    "0-16383",
    "33328080-34028784",
    "36669144-37416533"
  ],
  "Bytes_transfered": 1464476,
  "Timing": 3.093672037124634
}

```

**Comment by vincentsarago** [comment]
done in https://github.com/developmentseed/tilebench/commit/b984c35af11542d3497dacfae8705e1b26e8526a
